
/* Tea Table */
INSERT INTO `Tea` (`ID`,`Name`,`Description`,`Image`) 
  VALUES  (1,'Crescent','Moon, receptivity, introspection',''),
          (3,'Sum','Total, together, net',''),
          (2,'Circle Segments','Legato, rationality, sleep',''),
          (4,'Fuller Circle Segment','Do not disturb',''),
          (5,'Waves','Movement, travel',''),
          (6,'Circle with a Spot','New start',''),
          (7,'Star','Success',''),
          (8,'Heart','Love',''),
          (9,'Horseshoe','Luck',''),
          (10,'Cup','Celebration',''),
          (11,'V','Strong emotion, fire',''),
          (12,'Spiral','Creativity',''),
          (13,'|||','Change',''),
          (14,'X','Stop',''),
          (15,'Wheel','Progress',''),
          (16,'Anchor','Stability',''),
          (17,'Chains','Responsibility',''),
          (18,'Key','Caution',''),
          (19,'Fish','Good fortune',''),
          (20,'Duck','Money',''),
          21,'Cloud','Trouble','');

/* Tarot Table */
INSERT INTO `Tarot` (`ID`,`Name`,`UpMeaning`,`DownMeaning`,`Love`,`YesNo`)                                                                                                                                                                                                                                                                                                                                                
  VALUES  (1,'The Fool','New beginnings, innocence, adventure','Recklessness, fearlessness, risk','Take a leap of faith','Yes'),
          (2,'The Magician','Willpower, creation, manifestation','Manipulation, illusions','If there\'s a cloud in the sky, watch out!','Yes'),
          (3,'The High Priestess','Intuitive, unconscious, divine feminine','Repressed feelings, withdrawal, silence','Make up or break up','Yes'),
          (4,'The Empress','Femininity, nurturing, fertility, abundance','Dependence, smothering, emptiness','Love is in the air','Yes'),
          (5,'The Emperor','Authority, structure, a father figure','Excessive control, rigidity, domination','You like being dominated?!','Yes'),
          (6,'The Hierophant','Spiritual wisdom, tradition, conformity, morality, ethics','Rebellion, subversiveness, freedom, personal beliefs','Be open to advice','Neither'),
          (7,'The Lovers','Love, harmony, partnerships, choices','Disbalance, one-sidedness, disharmony','Soulmate or side piece in your vicinity','Yes'),
          (8,'The Chariot','Direction, control, willpower, determination, success, action','Lack of control, opposition, lack of direction, self-discipline','You do you','Yes'),
          (9,'Strength','Strength, courage, compassion, focus, persuasion, influence','Self-doubt, weakness, insecurity, low energy, raw emotion','You don\'t have to be the only one pulling the weight','Yes'),
          (10,'The Hermit','Wisdom, soul searching, solitude, spiritual enlightenment, receiving or giving guidance','Loneliness, isolation, paranoia, sadness, being overcome or paralyzed by fear','Single and ready to single','Yes'),
          (11,'Wheel of Fortune','Chance, destiny and fate, karma, turning points, life cycles','Upheaval, lousy luck, unwelcome change, setbacks, external forces','Things are looking good','Yes'),
          (12,'Justice','Fairness, integrity, legal disputes, cause and effect, life lessons','Injustice, dishonesty, failure to take responsibility, deceitful practices, negative karma','You\'re going to get what you deserve','Neutral'),
          (13,'The Hanged Man','Letting go, sacrificing, pausing to reflect, uncertainty, spiritual development','Discontentment, stagnation, negative patterns, no solution, fear of sacrifice','RIP your love life','Maybe'),
          (14,'Death','Ending of a cycle, transitions, getting rid of excess, powerful movement, resolutions','Resisting change, fear of new beginnings, dependency, repeating negative patterns','You need to move on','Yes'),
          (15,'Temperance','Balance, moderation, good health, cooperating with others, finding solutions','Imbalance, discord, hastiness, overindulgence, risky behavior','Move in','Yes'),
          (16,'The Devil','Material focus, trapped in bondage, addictions and depression, negative thinking, betrayal','Overcoming addiction, independence, reclaiming power, detachment, freedom','It\'s not looking so hot','No'),
          (17,'The Tower','Intense and sudden change, release, painful loss, tragedy, revelation','Resisting change, avoiding tragedy, a narrow escape, delaying what is inevitable','They\'re leaving you, if you\'re not alone already','No'),
          (18,'The Start','Hope, renewal, creativity and inspiration, generosity, healing','Despair, lack of hope, creative block, boredom, focusing on the negative','It\'s looking good actually','Yes'),
          (19,'The Moon','Fear, anxiety, confusion, delusion, risk','Overcoming fear, finding the truth, conquering anxiety, gaining clarity','Good sign for lesbians','No'),
          (20,'The Sun','Happiness, fertility, success, optimism, truth','Sadness, procrastination, pessimism, lies, failure','Wait no more!','Yes'),
          (21,'Judgement','Reflection, inner calling, reckoning, awakening, rebirth, absolution','Feeling down, self-doubt, missing the call fearlessness','I don\'t know, you determine your life','Yes'),
          (22,'The World','Fulfillment, harmony, completion, integration, travel, unity','Incompletion, shortcuts, delays, emptiness','You\'re either going get everything you want or nothing','Yes'),
          (23,'Ace of Wands','creation, willpower, inspiration, desire','Lack of energy, lack of passion, boredom','Start as friends','Yes'),
          (24,'Two of Wands','Planning, making decisions, leaving home','Fear of change, playing safe, bad planning','Sometimes people are boring','Yes'),
          (25,'Three of Wands','Looking ahead, expansion, rapid growth','Obstacles, delays, frustration','Spice it up a little','Neutral'),
          (26,'Four of Wands','Community, home, celebration','Lack of support, transience, home conflicts','Put a ring on it','Yes'),
          (27,'Five of Wands','Competition, rivalry, conflict','Avoiding conflict, respecting differences','Fight for love','Neither'),
          (28,'Six of Wands','Victory, success, public reward','Excess pride, lack of recognition, punishment','All you do is win','Yes'),
          (29,'Seven of Wands','Perseverance, defensive, maintaining control','Give up, destroyed confidence, overwhelmed','Say bye to you\'re relationship~','No'),
          (30,'Eight of Wands','Rapid action, movement, quick decisions','Panic, waiting, slowdown','This is your warning','Yes'),
          (31,'Nine of Wands','Resilience, grit, last stand ','Exhaustion, fatigue, questioning motivations','Poor you','No'),
          (32,'Ten of Wands','Accomplishment, responsibility, burden','Inability to delegate, overstressed, burnt out','All they do is bring pain','Neutral'),
          (33,'Page of Wands','Exploration, excitement, freedom','Lack of direction, procrastination, creating conflict','It\'s not serious','Neutral'),
          (34,'Knight of Wands','Action, adventure, fearlessness','Anger, impulsiveness, recklessness','The grass is greener on the other side','Yes'),
          (35,'Queen of Wands','Courage, determination, joy ','Selfishness, jealousy, insecurities','You do you, Queen','Neutral'),
          (36,'King of Wands','Big picture, leader, overcoming challenges','Impulsive, overbearing, unachievable expectations','Time to settle','Maybe'),
          (37,'Ace of Cups','New feelings, spirituality, intuition','Emotional loss, blocked creativity, emptiness','Your feelings are valid and ready to bloom','Yes'),
          (38,'Two of Cups','Unity, partnership, connection','Imbalance, broken communication, tension','Looks good to me','No'),
          (39,'Three of Cups','Friendship, community, happiness','Overindulgence, gossip, isolation','Looking lucky in the love department','Yes'),
          (40,'Four of Cups','Apathy, contemplation, disconnectedness','Sudden awareness, choosing happiness, acceptance','Alone not lonely amirite?','No'),
          (41,'Five of Cups','Loss, grief, self-pity','Acceptance, moving on, finding peace','It\'s not you, it\'s uh...','No'),
          (42,'Six of Cups','Familiarity, happy memories, healing','Moving forward, leaving home, independence','Focus on the present','Neutral'),
          (43,'Seven of Cups','Searching for purpose, choices, daydreaming','Lack of purpose, diversion, confusion','So many fishes in the sea, Captain!','Neutral'),
          (44,'Eight of Cups','Walking away, disillusionment, leaving behind','Avoidance, fear of change, fear of loss','Are you really happy?','No'),
          (45,'Nine of Cups','Satisfaction, emotional stability, luxury','Lack of inner joy, smugness, dissatisfaction','Looks like things are heating up','Yes'),
          (46,'Ten of Cups','Inner happiness, fulfillment, dreams coming true','Shattered dreams, broken family, domestic disharmony','Looks like sunshine','Yes'),
          (47,'Page of Cups','Happy surprise, dreamer, sensitivity','Emotional immaturity, insecurity, disappointment','it\'s a time for someone sensitive and mature','Yes'),
          (48,'Knight of Cups','Following the heart, idealist, romantic','Moodiness, disappointment','Good vibes all around','Yes'),
          (49,'Queen of Cups','Compassion, calm, comfort','Martyrdom, insecurity, dependence','Put yourself first in the relationship','Neutral'),
          (50,'King of Cups','Compassion, control, balance','Coldness, moodiness, bad advice','Things are looking stable','Yes'),
          (51,'Ace of Swords','Breakthrough, clarity, sharp mind','Confusion, brutality, chaos','Deep in love or deep in hate','Yes'),
          (52,'Two of Swords','difficult choices, indecision, stalemate','lesser of two evils, no right choice, confusion','Well matched with a lot in common','Maybe'),
          (53,'Three of Swords','Heartbreak, suffering, grief','Recovery, forgiveness, moving on','There\'s a lot of heartache T.T','No'),
          (54,'Four of Swords','Rest, restoration, contemplation','Restlessness, burnout, stress','It really depends on how you\'re feeling','Neutral'),
          (55,'Five of Swords','Unbridled ambition, win at all costs, sneakiness','Lingering resentment, desire to reconcile, forgiveness','I smell a little cheating','No'),
          (56,'Six of Swords','Transition, leaving behind, moving on','Emotional baggage, unresolved issues, resisting transition','Maybe travel a little first','Yes'),
          (57,'Seven of Swords','Deception, trickery, tactics and strategy','Coming clean, rethinking approach, deception','Wake up','No'),
          (58,'Eight of Swords','Imprisonment, entrapment, self-victimization','Self acceptance, new perspective, freedom','Don\'t get trapped','No'),
          (59,'Nine of Swords','Anxiety, hopelessness, trauma','Hope, reaching out, despair','Be wary, but don\'t let you\'re insecurities get the best of you','Neutral'),
          (60,'Ten of Swords','Failure, collapse, defeat','Can\'t get worse, only upwards, inevitable end','There\'s no good outcome','No'),
          (61,'Page of Swords','Curiosity, restlessness, mental energy','Deception, manipulation, all talk','Cut the haters out','No'),
          (62,'Knight of Swords','Action, impulsiveness, defending beliefs','No direction, disregard for consequences, unpredictability','I sense a lot anger','No'),
          (63,'Queen of Swords','Complexity, perceptiveness, clear mindedness','Cold hearted, cruel, bitterness','I sense some troubles ahead','No'),
          (64,'King of Swords','Head over heart, discipline, truth','Manipulative, cruel, weakness','love is not the priority','No'),
          (65,'Ace of Pentacles','Opportunity, prosperity, new venture','Lost opportunity, missed chance, bad investment','Hmmm depends. Either good or brutal','Yes'),
          (66,'Two of Pentacles','Balancing decisions, priorities, adapting to change','Loss of balance, disorganized, overwhelmed','I sense a little cheaty and infidelity','Maybe'),
          (67,'Three of Pentacles','Teamwork, collaboration, building','Lack of teamwork, disorganized, group conflict','It\'s a time for learning','Yes'),
          (68,'Four of Pentacles','Conservation, frugality, security','Greediness, stinginess, possessiveness','Someone\'s a little possessive...','Yes'),
          (69,'Five of Pentacles','Need, poverty, insecurity','Recovery, charity, improvement','You can make it work if you both put in work','No'),
          (70,'Six of Pentacles','Charity, generosity, sharing','Strings attached, stinginess, power and domination','It\'s good for now','Neutral'),
          (71,'Seven of Pentacles','Hard work, perseverance, diligence','Work without results, distractions, lack of rewards','I\'m sensing some good vibes coming your way','Yes'),
          (72,'Eight of Pentacles','Apprenticeship, passion, high standards','Lack of passion, uninspired, no motivation','Keep your eyes on the prize','Yes'),
          (73,'Nine of Pentacles','Fruits of labor, rewards, luxury','Reckless spending, living beyond means, false success','Settle down, but also spice it up','Yes'),
          (74,'Ten of Pentacles','Legacy, culmination, inheritance','Fleeting success, lack of stability, lack of resources','I\'m sensing a period of stability','Yes'),
          (75,'Page of Pentacles','Ambition, desire, diligence','Lack of commitment, greediness, laziness','Not seeing a lot of love','No'),
          (76,'Knight of Pentacles','Efficiency, hard work, responsibility','Laziness, obsessiveness, work without reward','I see commitment, just not right now','Yes'),
          (77,'Queen of Pentacles','Practicality, creature comforts, financial security','Self-centeredness, jealousy, smothering','Now\'s not the time for an affair','Yes'),
          (78,'King of Pentacles','Abundance, prosperity, security','Greed, indulgence, sensuality','It\'s a good time to settle down if you want','Yes');            